image: node:8
stages:
- setup
- verify
- deploy
yarn:
  stage: setup
  cache:
    paths:
    - node_modules/
    - .yarn-cache/
  script:
  - npm install -g yarn
  - yarn --cache-folder=.yarn-cache
lint:
  stage: verify
  cache:
    policy: pull
    paths:
    - node_modules/
  script: node_modules/.bin/gulp lint
pages:
  stage: deploy
  only:
  - master
  cache:
    policy: pull
    paths:
    - node_modules/
  script:
  - node_modules/.bin/gulp build:preview
  # FIXME figure out a way to avoid copying these files to preview site
  - rm -rf public/_/{helpers,layouts,partials}
  artifacts:
    paths:
    - public
