image: node:8
stages:
- setup
- verify
yarn:
  stage: setup
  script:
  - npm install -g yarn
  - yarn --cache-folder=.yarn-cache
  cache:
    paths:
    - node_modules/
    - .yarn-cache/
lint:
  stage: verify
  cache:
    policy: pull
    paths:
    - node_modules/
  script: node_modules/.bin/gulp lint
